## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
x = np.zeros(10)
print(x)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Создать вектор размера 10, заполненный единицами

In [5]:
x = np.ones(10)
print(x)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


Создать вектор размера 10, заполненный числом 2.5

In [6]:
x = np.ones(10)*2.5
print(x)

[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
x = np.zeros(10)
x[4] = 1
print(x)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


Развернуть вектор (первый становится последним)

In [8]:
x = np.arange(10)
x = x[::-1]
print(x)

[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [10]:
A = np.arange(9)
A = A.reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [11]:
x = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(x))

(array([0, 1, 4]),)


Создать 3x3 единичную матрицу

In [12]:
A = np.ones(9)
A = A.reshape(3,3)
print(A)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


Создать массив 3x3x3 со случайными значениями

In [13]:
A = np.random.random((3,3,3))
print(A)

[[[ 0.38800114  0.08332696  0.40850162]
  [ 0.07912183  0.4368567   0.04157331]
  [ 0.41841792  0.01479884  0.64637704]]

 [[ 0.83931651  0.09612709  0.90370577]
  [ 0.09847413  0.83040972  0.96181459]
  [ 0.75497354  0.94887978  0.93071969]]

 [[ 0.46248334  0.19865513  0.42461939]
  [ 0.83785547  0.78946374  0.98537588]
  [ 0.24241335  0.27898868  0.67740944]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [15]:
x = np.random.random((30))
print(x.mean())

0.491642721718


Перемножить матрицы 5x3 и 3x2

In [17]:
A = np.ones(15).reshape(5,3)
B = np.ones(6).reshape(3,2)
C = np.dot(A,B)
print(A)
print(B)
print(C)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [18]:
x = np.linspace(0, 1, 10)
print(x)
x[x.argmax()] = 0.5
x[x.argmin()] = 0.5
print(x)

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]
[ 0.5         0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  0.5       ]


Заменить максимальный элемент на ноль

In [19]:
print(x)
x[x.argmax()] = 0
print(x)

[ 0.5         0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  0.5       ]
[ 0.5         0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.          0.5       ]


Преобразовать массив из float в int

In [20]:
x = x.astype(int)
print(x)

[0 0 0 0 0 0 0 0 0 0]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [21]:
A = np.random.random(20).reshape(10,2)
print(A)
A_1 = A[:,np.newaxis,:]
A_2 = A[np.newaxis,:,:]
print(np.sum((A_1 - A_2)**2, axis = -1)**0.5)

[[ 0.54745189  0.05897069]
 [ 0.13902722  0.37282065]
 [ 0.95329758  0.71204469]
 [ 0.65755894  0.51496096]
 [ 0.93449748  0.83955252]
 [ 0.3225405   0.66055344]
 [ 0.43158508  0.06417821]
 [ 0.67056023  0.34354707]
 [ 0.40009933  0.89252129]
 [ 0.56033206  0.28796018]]
[[ 0.          0.51508495  0.76890596  0.46909561  0.87127049  0.64225146
   0.11598377  0.31006351  0.84647467  0.22935145]
 [ 0.51508495  0.          0.88210497  0.53766068  0.92228605  0.34127304
   0.42526493  0.5323385   0.58159041  0.42976629]
 [ 0.76890596  0.88210497  0.          0.35539182  0.12888634  0.63285531
   0.83181423  0.46446841  0.58189355  0.57816051]
 [ 0.46909561  0.53766068  0.35539182  0.          0.42667861  0.3652869
   0.5042512   0.17190624  0.45698714  0.24694619]
 [ 0.87127049  0.92228605  0.12888634  0.42667861  0.          0.63759863
   0.92418948  0.56185787  0.53701682  0.66652371]
 [ 0.64225146  0.34127304  0.63285531  0.3652869   0.63759863  0.
   0.60626244  0.47075553  0.24459038  

Случайно расположить p элементов в 2D массив

In [26]:
p = 4
k = 2
x = np.ones(p)
print(x)
A = np.zeros(p*k)
print(A)
y = np.random.choice(np.arange(p*k), p, replace=False)
print(y)
np.put(A, y, x)
print(A.reshape(p,k))

[ 1.  1.  1.  1.]
[ 0.  0.  0.  0.  0.  0.  0.  0.]
[5 4 1 2]
[[ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]
 [ 0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [29]:
x = [1, 2, 3, 4, 5]
A = np.zeros(17)
np.put(A, np.arange(5)*4, x)
print(A)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

In [32]:
A = np.arange(20)
print(A)
for i in range(np.random.randint(1,3)):
    np.put(A, np.random.choice(np.arange(20), 6, replace=True), [i*3])
print(A)
counter = np.bincount(A)
print(counter)
print(counter.argmax())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  3  3  3  3  0  7  8  3  0 11  0 13  3 15  3 17 18 19]
[4 1 0 7 0 0 0 1 1 0 0 1 0 1 0 1 0 1 1 1]
3


Найти n наибольших значений в массиве

In [35]:
A = np.random.random(10)
n = 3
print(np.sort(A)[-n:])

[ 0.56165272  0.94497795  0.99245455]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

Посмотреть первые 5 записей

Сколько наблюдений в наборе данных?


Сколько столбцов в наборе данных?

Напечатайте все названия столбцов

Какое название у 105 столбца?

Какой тип наблюдений в 105 столбце?

Как проиндексирован набор данных?

Каково значение имени продукта в 19-м наблюдении?

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?